---
- name: Patching - Update packages
  package:
    name: "{{ packages }}"
    state: "{{ state }}"
  register: package_results
  become: true
  ignore_errors: yes
  async: 3600
  poll: 30

- name: Invoke error handler
  include_role:
    name: { role: error_handling, status_code: "Package update encountered an error"}
  when: package_results.rc != 0