---
- name: Update patch_step fact
  set_fact: patch_step="prepatching_remove_old_kernels"
  no_log: true

- name: Pre-patching - delete old kernels
  script: ../supporting_tools/remove_old_kernels.sh
